const Courses = [
  {
    id: "1",
    title: "Web Development",
    Instructorname: "John Doe",
    Enrolled: "100",
    Enrollmentstatus: "Open",
    duration: "2 months",
    schedule: "Monday, Wednesday, Friday",
    location: "Online",
    Pre_requisite: "None",
    Syllabus: "HTML, CSS, JavaScript, React, Node, Express, MongoDB",
    image: require("../../assets/course/web.jpg"),
    description:
      "Web development course containing html, css, javascript, react, node, express, mongodb, etc.",
    course1: "html",
    course2: "css",
    course3: "javascript",
    price: 5000,
  },
  {
    id: "2",
    title: "Graphic Designing ",
    Instructorname: "harry Doe",
    Enrolled: "100",
    Enrollmentstatus: "Closed",
    duration: "2 months",
    schedule: "Monday, Wednesday, Friday, Sunday",
    location: "Online",
    Pre_requisite: "Basic Computer Knowledge",
    Syllabus: "Photoshop, Figma, Adobe XD",
    image: require("../../assets/course/graphic.jpg"),
    description:
      "Graphic designing course containing photoshop, figma, adobe xd, etc. ",
    course1: "Photoshop",
    course2: "Figma",
    course3: "Adobe XD",
    price: 3000,
  },
  {
    id: "3",
    title: "Coding Fundamentals",
    Instructorname: "Maxwell Doe",
    Enrolled: "120",
    Enrollmentstatus: "In Progress",
    duration: "4 months",
    schedule: "Monday, Wednesday, Friday",
    location: "Online",
    Pre_requisite: "basic programming knowledge",
    Syllabus: "JavaScript, Algorithm, Data Structure",
    image: require("../../assets/course/coding.jpg"),
    description:
      "Coding fundamentals course containing javascript, algorithm, data structure, etc. ",
    course1: "JavaScript",
    course2: "Algorithm",
    course3: "Data Structure",
    price: 1000,
  },
  {
    id: "4",
    title: "Ethical Hacking",
    Instructorname: "john maxwell Doe",
    Enrolled: "500",
    Enrollmentstatus: "Open",
    duration: "6 months",
    schedule: "Monday, Wednesday, Friday",
    location: "Online",
    Pre_requisite: "None",
    Syllabus: "Testing, Exploitation, Linux OS",
    image: require("../../assets/course/eth.jpg"),
    description:
      "Ethical hacking course containing testing, exploitation, linux os, etc. ",
    course1: "Testing",
    course2: "Exploitation",
    course3: "Linux OS",
    price: 6000,
  },
  {
    id: "5",
    title: "Web Development Advanced",
    Instructorname: "john Doe",
    Enrolled: "400",
    Enrollmentstatus: "Open",
    duration: "8 months",
    schedule: "Monday, Wednesday, Friday",
    location: "Online",
    Pre_requisite: "Basic Web Development Knowledge",
    Syllabus: "HTML, CSS, JavaScript, React, Node, Express, MongoDB",
    image: require("../../assets/course/web.jpg"),
    description:
      " Web development course containing html, css, javascript, react, node, express, mongodb, etc. ",
    course1: "html",
    course2: "css",
    course3: "javascript",
    price: 5000,
  },
  {
    id: "6",
    title: "Android Development",
    Instructorname: "Indresh Doe",
    Enrolled: "450",
    Enrollmentstatus: "Open",
    duration: "8 months",
    schedule: "Monday, Wednesday, Friday",
    location: "Online",
    Pre_requisite: "Basic Web Development Knowledge",
    Syllabus: "React Native, Java, Kotlin",
    image: require("../../assets/course/web.jpg"),
    description:
      " Web development course containing html, css, javascript, react, node, express, mongodb, etc. ",
    course1: "html",
    course2: "css",
    course3: "javascript",
    price: 5000,
  },
];

export default Courses;
